package com.rkstech.bookyourshow.models;

import jakarta.persistence.*;
import lombok.Builder;
import lombok.Getter;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.util.Date;
@Getter
@Setter
//tells jps this is my parent class all my entity will have these value in database but don't add them to child objects add it to parent objects
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class) // tells hibernate to look at th table and see if new row is created for updated at ad created at
public abstract class BaseModel {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;


    @CreatedDate // automatically generated by jpa
    @Temporal(value = TemporalType.TIMESTAMP) // spatial and temporal  -> spatial relate to space and temporal relates to time It just tells hibernate to generate the Timestamp
    private Date createdAt;

    @LastModifiedDate //// automatically generated by jpa
    @Temporal(value = TemporalType.TIMESTAMP) // spatial and temporal  -> spatial relate to space and temporal relates to time It just tells hibernate to generate the Timestamp
    private Date updatedAt;
}
